/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\temp\\awesome-css\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-d3bebd6a",
    path: "/handbook/transition.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3bebd6a").then(next)
    },
  },
  {
    name: "v-71b5b85d",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71b5b85d").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4b67aa6b",
    path: "/result/best-way-to-center-element.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b67aa6b").then(next)
    },
  },
  {
    name: "v-17d17d01",
    path: "/result/pullCurtain.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17d17d01").then(next)
    },
  },
  {
    name: "v-226d16ea",
    path: "/selector/active.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-226d16ea").then(next)
    },
  },
  {
    name: "v-de1785ea",
    path: "/selector/after_before.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de1785ea").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]