/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "国内css平台从业者交流",
  "description": "awesome-css",
  "base": "/awesome-css/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-71b5b85d",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "学前必读",
          "slug": "学前必读"
        },
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果"
        },
        {
          "level": 2,
          "title": "留言评论",
          "slug": "留言评论"
        },
        {
          "level": 2,
          "title": "感谢指正",
          "slug": "感谢指正"
        },
        {
          "level": 2,
          "title": "声明",
          "slug": "声明"
        },
        {
          "level": 2,
          "title": "勘误及提问",
          "slug": "勘误及提问"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "2022/5/19 下午8:52:05",
      "lastUpdatedTimestamp": 1652964725000
    },
    {
      "frontmatter": {},
      "regularPath": "/result/best-way-to-center-element.html",
      "relativePath": "result/best-way-to-center-element.md",
      "key": "v-4b67aa6b",
      "path": "/result/best-way-to-center-element.html",
      "headers": [
        {
          "level": 2,
          "title": "实现水平垂直居中最便捷的方法",
          "slug": "实现水平垂直居中最便捷的方法"
        }
      ],
      "lastUpdated": "2022/5/19 上午11:00:59",
      "lastUpdatedTimestamp": 1652929259000
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/animation.html",
      "relativePath": "handbook/animation.md",
      "key": "v-6fb72b5d",
      "path": "/handbook/animation.html",
      "headers": [
        {
          "level": 2,
          "title": "animation属性",
          "slug": "animation属性"
        },
        {
          "level": 2,
          "title": "子属性",
          "slug": "子属性"
        },
        {
          "level": 2,
          "title": "多个步骤",
          "slug": "多个步骤"
        },
        {
          "level": 2,
          "title": "多个动画",
          "slug": "多个动画"
        },
        {
          "level": 2,
          "title": "表现",
          "slug": "表现"
        },
        {
          "level": 2,
          "title": "浏览器支持",
          "slug": "浏览器支持"
        }
      ],
      "lastUpdated": "2022/5/19 下午8:52:05",
      "lastUpdatedTimestamp": 1652964725000
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/transition.html",
      "relativePath": "handbook/transition.md",
      "key": "v-d3bebd6a",
      "path": "/handbook/transition.html",
      "headers": [
        {
          "level": 2,
          "title": "演示：",
          "slug": "演示"
        },
        {
          "level": 2,
          "title": "指定要转换的属性",
          "slug": "指定要转换的属性"
        }
      ],
      "lastUpdated": "2022/5/18 上午11:45:28",
      "lastUpdatedTimestamp": 1652845528000
    },
    {
      "frontmatter": {},
      "regularPath": "/result/css-masonry-flexbox.html",
      "relativePath": "result/css-masonry-flexbox.md",
      "key": "v-41f7e25b",
      "path": "/result/css-masonry-flexbox.html",
      "headers": [
        {
          "level": 2,
          "title": "瀑布流效果",
          "slug": "瀑布流效果"
        },
        {
          "level": 2,
          "title": "效果",
          "slug": "效果"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/result/pullCurtain.html",
      "relativePath": "result/pullCurtain.md",
      "key": "v-17d17d01",
      "path": "/result/pullCurtain.html",
      "headers": [
        {
          "level": 2,
          "title": "让我们设置一些 CSS 变量",
          "slug": "让我们设置一些-css-变量"
        },
        {
          "level": 2,
          "title": "是时候拉开帷幕了",
          "slug": "是时候拉开帷幕了"
        },
        {
          "level": 2,
          "title": "制作粘性内容",
          "slug": "制作粘性内容"
        },
        {
          "level": 2,
          "title": "“拉开窗帘”演示",
          "slug": "拉开窗帘-演示"
        }
      ],
      "lastUpdated": "2022/5/18 下午1:32:44",
      "lastUpdatedTimestamp": 1652851964000
    },
    {
      "frontmatter": {},
      "regularPath": "/result/css-carousel.html",
      "relativePath": "result/css-carousel.md",
      "key": "v-7c40000b",
      "path": "/result/css-carousel.html",
      "headers": [
        {
          "level": 2,
          "title": "轮播图效果",
          "slug": "轮播图效果"
        },
        {
          "level": 2,
          "title": "效果",
          "slug": "效果"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/selector/active.html",
      "relativePath": "selector/active.md",
      "key": "v-226d16ea",
      "path": "/selector/active.html",
      "lastUpdated": "2022/5/19 上午11:00:59",
      "lastUpdatedTimestamp": 1652929259000
    },
    {
      "frontmatter": {},
      "regularPath": "/selector/after_before.html",
      "relativePath": "selector/after_before.md",
      "key": "v-de1785ea",
      "path": "/selector/after_before.html",
      "headers": [
        {
          "level": 2,
          "title": "content的值：",
          "slug": "content的值"
        },
        {
          "level": 2,
          "title": "浏览器兼容：",
          "slug": "浏览器兼容"
        }
      ],
      "lastUpdated": "2022/5/19 上午11:00:59",
      "lastUpdatedTimestamp": 1652929259000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/webVueBlog/awesome-css",
    "repoLabel": "Github",
    "editLinks": true,
    "editLinkText": "编辑此页",
    "lastUpdated": "上次更新",
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "星星♥",
        "link": "https://github.com/webVueBlog/awesome-css"
      },
      {
        "text": "其它",
        "items": [
          {
            "text": "博客",
            "items": [
              {
                "text": "Github",
                "link": "https://github.com/webVueBlog"
              },
              {
                "text": "博客",
                "link": "https://1024bibi.com"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "学前必读",
            "path": "/"
          }
        ]
      },
      {
        "title": "属性",
        "path": "/handbook/transition",
        "collapsable": false,
        "children": [
          {
            "title": "transition",
            "path": "/handbook/transition"
          },
          {
            "title": "animation",
            "path": "/handbook/animation"
          }
        ]
      },
      {
        "title": "选择器",
        "path": "/selector/after_before",
        "collapsable": false,
        "children": [
          {
            "title": "::before和::after",
            "path": "/selector/after_before"
          },
          {
            "title": ":active",
            "path": "/selector/active"
          }
        ]
      },
      {
        "title": "效果",
        "path": "/result/pullCurtain",
        "collapsable": false,
        "children": [
          {
            "title": "拉起窗帘",
            "path": "/result/pullCurtain"
          },
          {
            "title": "实现水平垂直居中最便捷的方法",
            "path": "/result/best-way-to-center-element"
          },
          {
            "title": "轮播图效果",
            "path": "/result/css-carousel"
          },
          {
            "title": "瀑布流效果",
            "path": "/result/css-masonry-flexbox"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}