/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "awesome-css",
  "description": "awesome-css",
  "base": "/awesome-css/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-71b5b85d",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "学前必读",
          "slug": "学前必读"
        },
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "效果",
          "slug": "效果"
        },
        {
          "level": 2,
          "title": "留言评论",
          "slug": "留言评论"
        },
        {
          "level": 2,
          "title": "感谢指正",
          "slug": "感谢指正"
        },
        {
          "level": 2,
          "title": "声明",
          "slug": "声明"
        },
        {
          "level": 2,
          "title": "勘误及提问",
          "slug": "勘误及提问"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "2022/5/18 上午11:45:28",
      "lastUpdatedTimestamp": 1652845528000
    },
    {
      "frontmatter": {},
      "regularPath": "/result/pullCurtain.html",
      "relativePath": "result/pullCurtain.md",
      "key": "v-17d17d01",
      "path": "/result/pullCurtain.html",
      "headers": [
        {
          "level": 2,
          "title": "让我们设置一些 CSS 变量",
          "slug": "让我们设置一些-css-变量"
        },
        {
          "level": 2,
          "title": "是时候拉开帷幕了",
          "slug": "是时候拉开帷幕了"
        },
        {
          "level": 2,
          "title": "制作粘性内容",
          "slug": "制作粘性内容"
        },
        {
          "level": 2,
          "title": "“拉开窗帘”演示",
          "slug": "拉开窗帘-演示"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/handbook/transition.html",
      "relativePath": "handbook/transition.md",
      "key": "v-d3bebd6a",
      "path": "/handbook/transition.html",
      "headers": [
        {
          "level": 2,
          "title": "演示：",
          "slug": "演示"
        },
        {
          "level": 2,
          "title": "指定要转换的属性",
          "slug": "指定要转换的属性"
        }
      ],
      "lastUpdated": "2022/5/18 上午11:45:28",
      "lastUpdatedTimestamp": 1652845528000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/webVueBlog/awesome-css",
    "repoLabel": "Github",
    "editLinks": true,
    "editLinkText": "编辑此页",
    "lastUpdated": "上次更新",
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "星星♥",
        "link": "https://github.com/webVueBlog/awesome-css"
      },
      {
        "text": "其它",
        "items": [
          {
            "text": "博客",
            "items": [
              {
                "text": "Github",
                "link": "https://github.com/webVueBlog"
              },
              {
                "text": "博客",
                "link": "https://1024bibi.com"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "学前必读",
            "path": "/"
          }
        ]
      },
      {
        "title": "属性",
        "path": "/handbook/transition",
        "collapsable": false,
        "children": [
          {
            "title": "transition",
            "path": "/handbook/transition"
          }
        ]
      },
      {
        "title": "效果",
        "path": "/result/transition",
        "collapsable": false,
        "children": [
          {
            "title": "拉起窗帘",
            "path": "/result/pullCurtain"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}